name: Browser Integration Tests

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      browser:
        required: true
        type: string
      compiler:
        required: false
        type: string
        default: ldc-latest

permissions:
  contents: read

jobs:
  test:
    name: ${{ inputs.browser }} (${{ inputs.os }})
    runs-on: ${{ inputs.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Install D compiler
        uses: dlang-community/setup-dlang@v2
        with:
          compiler: ${{ inputs.compiler }}

      - name: Run integration tests
        run: dub test -c integration --d-version=${{ inputs.browser }}