name: CI (3)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/browser-integration.yml
    with:
      os: windows-latest
      browser: chrome
