name: CI (6)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/browser-integration-tests.yml
    with:
      os: windows-latest
      browser: firefox
