name: CI (5)

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  test:
    uses: ./.github/workflows/browser-integration.yml
    with:
      os: ubuntu-latest
      browser: firefox
